/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__PPOAgent
#define __PYX_HAVE__PPOAgent

#include "Python.h"

#ifndef __PYX_HAVE_API__PPOAgent

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *createPPOAgent(float *, int, int);
__PYX_EXTERN_C int infer(PyObject *, float *);
__PYX_EXTERN_C void finish(PyObject *, float *);

#endif /* !__PYX_HAVE_API__PPOAgent */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initPPOAgent(void);
#else
PyMODINIT_FUNC PyInit_PPOAgent(void);
#endif

#endif /* !__PYX_HAVE__PPOAgent */
